name: Deploy to DigitalOcean (DockerHub)

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_BACKEND: sirlikont123/todo-backend
  IMAGE_FRONTEND: sirlikont123/todo-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push backend
        run: |
          docker build -t $IMAGE_BACKEND:latest ./backend
          docker push $IMAGE_BACKEND:latest

      - name: Build and push frontend
        run: |
          docker build -t $IMAGE_FRONTEND:latest ./frontend-react
          docker push $IMAGE_FRONTEND:latest
